In [1673]:
import numpy as np

#1-d Array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1674]:
#2-D Array
arr2=np.array([[1,2,3,],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [1675]:
# creating array of zeros
arr3=np.zeros((2,3))# 2 row and 3 column
print(arr3)



[[0. 0. 0.]
 [0. 0. 0.]]


In [1676]:
# creating array of ones
arr4=np.ones((3,5))
print(arr4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [1677]:
#creating identity matrices
arr5=np.identity((5))
print(arr5)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [1678]:
#arange---->count the

arr6=np.arange(10)
print(arr6)

[0 1 2 3 4 5 6 7 8 9]


In [1679]:
arr7=np.arange(10,25)
print(arr7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [1680]:
arr8=np.arange(10,25,2)
print(arr8)

[10 12 14 16 18 20 22 24]


In [1681]:
#linspace
arr9=np.linspace(0,20,10)
print(arr9)

print()

arr10=np.linspace(4,40,10)
print(arr10)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]

[ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40.]


In [1682]:
# copy ---->used to copy the array
arr11=arr10.copy()
print(arr10)

[ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40.]


In [1683]:
#shape----> use to know the shape of the array
#shape
print(arr1)
print(arr1.shape)

print()

print(arr4)
print(arr4.shape)

[1 2 3 4 5]
(5,)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 5)


In [1684]:
# multidiamentional array
arr12=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr12)
print(arr12.shape) # (2 rows , 2 column, 2 element)
print(arr12.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [1685]:
#size---> returns the total number of elements in array
print(arr12.size)

8


In [1686]:
#itemsize----> return much memory  each element in taking in memeory
print(arr12.itemsize)

8


In [1687]:
# dtype---> return the data -type  of array
print(arr12)
print(arr12.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
int64


In [1688]:
py_list=[1,'2',3,5,4,True]
np_array=np.array([1,2.5,3,4,"hello"])

type_list=[]
for x in py_list:
  type_list.append(type(x))

print("Python list types",type_list)
print("numpy array type",np_array.dtype)




Python list types [<class 'int'>, <class 'str'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'bool'>]
numpy array type <U32


## list vs Numpy
* FAST
* Less memory
* convenient

In [1689]:
# less Memory ---> numpy take less memory as compare to python list
import sys
py_list=list(range(10000))
np_array=np.arange(10000)

print("Python list size",sys.getsizeof(py_list),"Bytes")
print("Numpy array size",np_array.nbytes,"Bytes")

Python list size 80056 Bytes
Numpy array size 80000 Bytes


In [1690]:
# Faster ---> Numpy Operational speed much faster than python list
import time

py_list=list(range(1000000))
start=time.time() # current Time
py_result=[]
for x in py_list:
  py_result.append(x*2)
end=time.time()
print("Python list Time",end-start)

np_array=np.arange(1000000)
start=time.time()
np_result=np_array*2 # Vectorization
end=time.time()
print("Numpy array list",end-start)

Python list Time 0.208420991897583
Numpy array list 0.0017266273498535156


# indexing & Sciling in numpy


In [1691]:
# 1D Array
arr13=np.arange(24)
print(arr13)

#indexing
print(arr13[7])
print(arr13[-2])

# sciling
print(arr13[6:10])
print(arr13[-6:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
7
22
[6 7 8 9]
[18 19 20 21 22]


In [1692]:
# multidiamentional matrics
# reshape---> convert the array into given matrics size

arr14=np.arange(24).reshape(6,4)
print(arr14)

print()

# indexing
print("Return rows of matrics:",arr14[2])

print()

# sciling
print("Return rows of matrics:\n",arr14[3:5])

# sciling rows and columns
print("return rows and column:",arr14[:,2]) # (rows_sciling,column_sciling)
print("return rows and column:\n",arr14[:,1:4])
print("return rows and column:\n",arr14[4:6,2:4])

print("return rows and column:\n",arr14[2:4,1:3])
print("return rows and column:\n",arr14[3:5,:3])
print("abc \n",arr15[0][2][:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Return rows of matrics: [ 8  9 10 11]

Return rows of matrics:
 [[12 13 14 15]
 [16 17 18 19]]
return rows and column: [ 2  6 10 14 18 22]
return rows and column:
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]
 [21 22 23]]
return rows and column:
 [[18 19]
 [22 23]]
return rows and column:
 [[ 9 10]
 [13 14]]
return rows and column:
 [[12 13 14]
 [16 17 18]]
abc 
 [ 8  9 10 11]


In [1]:
# multiblock & multidiamentional
arr15=np.arange(32).reshape(2,4,4) #(matrics,row, column)
print(arr15)

#indexing
print("return matrics\n",arr15[0])
print("return matrics\n",arr15[1])

print("return first row and first matrics \n",arr15[0][0])
print("return second row and second matrics \n",arr15[1][1])
print("return third row and first matrics \n",arr15[0][3])
print("return third row and first matrics \n",arr15[0][0][1])
print("return third row and first matrics \n",arr15[0][2][2])

print("return third row and first matrics \n",arr15[1][2][0])

# sciling
print("return all matrics , first row,second column ",arr15[0][0])
print("return all matrics , first row,second column ",arr15[1][0])
print("\n",arr15[0][:][:])
print("\n",arr15[1][:][:])




NameError: name 'np' is not defined

In [1694]:
# numpy iteration
for i in np.nditer(arr12):
  print(i)

1
2
3
4
5
6
7
8


In [1695]:
arr=np.arange(24).reshape(6,4)
print(arr)
for i in np.nditer(arr[4]):
  print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
16
17
18
19


In [1696]:
for i in np.nditer(arr15[1][3][1]):
  print(i)

29


In [1697]:
# Numpy operation
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

# add
print(arr1+arr2)

#sub
print(arr1-arr2)

# multiplication
print(arr1*arr2)
print(arr1*2)

# division
print(arr1/arr2)
print(arr1/2)

print(arr1>3)
print(arr1[arr1>3])

print([arr1%2!=0])

[ 5  7  9 11 13 15]
[-3 -3 -3 -3 -3 -3]
[ 4 10 18 28 40 54]
[ 2  4  6  8 10 12]
[0.25       0.4        0.5        0.57142857 0.625      0.66666667]
[0.5 1.  1.5 2.  2.5 3. ]
[False False False  True  True  True]
[4 5 6]
[array([ True, False,  True, False,  True, False])]


In [1698]:
# Numpy operation
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])

# add
print(arr1+arr2)

#sub
print(arr1-arr2)

# multiplication
print(arr1*arr2)
print(arr1*2)

# division
print(arr1/arr2)
print(arr1/2)

print(arr1>3)
print(arr1[arr1>3])

[[ 5  7  9]
 [11 13 15]]
[[-3 -3 -3]
 [-3 -3 -3]]
[[ 4 10 18]
 [28 40 54]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[False False False]
 [ True  True  True]]
[4 5 6]
