# Numpy

In [2]:
import numpy as np

In [2]:
arr= np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr= np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


# Diamention in array

In [4]:
arr= np.array(20)
print(arr)
print(type(arr))
print(arr.ndim) #check the diamention of array

20
<class 'numpy.ndarray'>
0


# 1-d array

In [5]:
arr= np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


# 2-d array

In [6]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [13]:
arr= np.array([[1.1,2.2,3.33],[4.44,5.67,6.98]])
print(arr)
print(arr.ndim)

[[1.1  2.2  3.33]
 [4.44 5.67 6.98]]
2


# 3-d array

In [14]:
arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


# check number of diamention Array

In [15]:
a= np.array(42) # 0 diamention
b= np.array([1,2,3,4]) #1 diamention
c= np.array([[1,2,3],[4,5,6]])# 2 diamention
d= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[6,7,8]]])# 3 diamention
#d= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)




0
1
2
3


# Create an Array

In [16]:
arr= np.array([1,2,3,4,5], ndmin=5) #create an Array
print(arr)
print("Number of Diamenision:",arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of Diamenision: 5


In [17]:
a=np.array([[[[[1, 2, 3, 4, 5]]]]])
print(a)
print("Number of Diamenision:",a.ndim)

[[[[[1 2 3 4 5]]]]]
Number of Diamenision: 5


# Numpy Array indexing

In [18]:
arr= np.array([1,2,3,4,5])
print(arr[0])
print(arr[3])
print(arr[-1])


1
4
5


# Get 3, 6, 8 element and ADD them

In [19]:
arr=[2,34,45,6,7,87,9,100,55,98,28,77,900]
print("3 Element is",arr[2])
print("6 Element is",arr[5])
print("8 Element is",arr[7])
print("Sum is",arr[2]+arr[5]+arr[7])

3 Element is 45
6 Element is 87
8 Element is 100
Sum is 232


# Access 2-D

In [20]:
arr= np.array([[1,2,3,4],[7,8,9,10]])
print("2nd element and row 1:",arr[0,1])
print(arr.ndim)

2nd element and row 1: 2
2


In [21]:
arr= np.array([[1,2,3,4],[7,8,9,10]])
print("3nd element and row 2:",arr[1,2])

3nd element and row 2: 9


In [22]:
arr= np.array([[1,2,3,4],[7,8,9,10]])
print("1nd element and row 2:",arr[1,1])

1nd element and row 2: 8


In [23]:
arr= np.array([[1,2,3,4],[7,8,9,10]])
print("last element and row 1:",arr[0,3])

last element and row 1: 4


In [24]:
#1 and last element and ADD them in 2-D
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("First Element ",arr[0,0])
print("Last Element ",arr[1,4])
print("Sum is ",arr[0,0]+arr[1,4])



First Element  10
Last Element  100
Sum is  110


# Access 3-D Array

In [25]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,0,2])

3


In [26]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,2])

9


In [27]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,2])

12


In [28]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,1])


5


In [29]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,1])

11


# Sciling Of Numpy Array

In [30]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [31]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [32]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[::])

[1 2 3 4 5 6 7]


In [33]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# Sciling in 2-D Array

In [34]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1:4])

[2 3 4]


In [35]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,0:5])

[1 2 3 4 5]


In [36]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [37]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,::2])

[ 6  8 10]


In [38]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,::-1])

[5 4 3 2 1]


In [39]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,::-1])

[10  9  8  7  6]


# Special Types of Arrays ( filled with specific value)

![](pic4.jpg)

# zeros

In [53]:
v=np.zeros(4)
print(v)
print()
v1=np.zeros((3,4))
print(v1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones

In [54]:
v=np.ones(4)
print(v)
print()
v1=np.ones((3,4))
print(v1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [55]:
x=np.empty(4)
print(x) #print only previous(last) value in memory


[1. 1. 1. 1.]


# Range

In [62]:
y=np.arange(4)
print(y)
print()
z=np.arange(1,6)
print(z)

[0 1 2 3]
[1 2 3 4 5]


# Diagonal

In [65]:
q=np.eye(4)
print(q)
print()
q1=np.eye(3,3)
print(q1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# LineSpace

In [69]:
d=np.linspace(1,10,num=5)
print(d)
print()
d=np.linspace(0,10,num=4)
print(d)

[ 1.    3.25  5.5   7.75 10.  ]

[ 0.          3.33333333  6.66666667 10.        ]


In [70]:
d=np.linspace(0,20,num=5)
print(d)

[ 0.  5. 10. 15. 20.]


# Creating Random Valued Arrays

# Random

![](pic5.jpg)

# rand()

In [73]:
var=np.random.rand(4)
print(var) #every print is random value between (0-1)



[0.13700983 0.68907892 0.40322884 0.78373308]


In [75]:
var1=np.random.rand(2,5)
print(var1) #every print is random value between (0-1)



[[0.01960081 0.60207682 0.41840869 0.26882525 0.27030883]
 [0.10313484 0.0714567  0.10254814 0.02184169 0.68597841]]


# randn()

In [78]:
var1=np.random.randn(5)# every print is random value is close to (0)

print(var1)

[-1.3552652  -0.12031355 -0.21305276  0.45528788 -0.53408443]


# randf()

In [81]:
var2=np.random.ranf(5)# every print is random value between [0-1)(zero is included and 1 is not included)

print(var2)

[0.62555955 0.44259856 0.73310174 0.97623313 0.97195521]


# randint()

In [88]:
# var3=np.random.randint(min,max,total_number) every print is random value given range
var3=np.random.randint(5,20,5)
print(var3)

[17 13 14 13  5]


![](pic6.jpg)

![](pic7.jpg)

![](pic8.jpg)

![](pic9.jpg)

# Checking the data types of an Array

In [40]:
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [41]:
arr=np.array(["Animal","CAT","Dog"])
print(arr.dtype)

<U6


# Creating Arrays with Defined data types

In [42]:
arr=np.array([1,2,3,4,5], dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [43]:
# Creating 4-Bytes Integers
arr=np.array([1,2,3,4,5], dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


# Numpy Array Shapes

the shape of an array is the number of element in each diamention

# Print the shape od 2-D array 

In [44]:
arr= np.array([[1,2,3,4],[5,6,7,8]]) # 2--> 1-d & 4--->Element
print(arr.shape)

(2, 4)


In [21]:
arr= np.array([1,2,3,4],ndmin=4)
print(arr)
print(arr.ndim)
print()
print(arr.shape)


[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# Reshape

In [30]:
var= np.array([1,2,3,4,5,6,7,8])
print(var)
print(var.ndim)
print()

e=var.reshape(4,2)
print(e)
print(e.ndim)



[1 2 3 4 5 6 7 8]
1

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2


In [31]:
var1= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var1)
print(var1.ndim)
print()

e=var1.reshape(2,3,2)
print(e)
print(e.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [33]:
var3= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()

x=var3.reshape(2,3,2)
print(x)
print(x.ndim)
print()

one=var3.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [45]:
arr= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]) # 1--> 1-d , 3--->2-d, & 4--->Element
print(arr.shape)

(1, 3, 4)


# Joining Numpy Array

In [46]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [47]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [48]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting Numpy Arrays

 Splitting Array In 3 parts

In [49]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


 Splitting Array In 4 parts

In [50]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ravel & Flatten

![](ss.JPG)

In [26]:
v2= np.array([1,2,3,4,5,6,7,8])
y=np.resize(v2,(3,2))

print(y.flatten())

[1 2 3 4 5 6]


In [29]:
v= np.array([1,2,3,4,5,6,7,8])
y=np.resize(v,(3,2))
print(y)

print(y.flatten(order="F"))

[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]


In [30]:
v= np.array([1,2,3,4,5,6,7,8])
y=np.resize(v,(3,2))
print(y)

print(y.flatten(order="c"))

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [33]:

v= np.array([1,2,3,4,5,6,7,8])
y=np.resize(v,(3,2))
print(y)

print("Flatten:",y.flatten(order="K"))
print("ravel:",y.ravel(order="A"))

[[1 2]
 [3 4]
 [5 6]]
Flatten: [1 2 3 4 5 6]
ravel: [1 2 3 4 5 6]


In [ ]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("Diamention is:",m.ndim)
arr=m.ravel()
print(arr)
print("Diamention is:",arr.ndim)


In [52]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("Diamention is:",m.ndim)
arr=m.flatten()
print(arr)
print("now the new Diamention is:",arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Diamention is: 3
[1 2 3 4 5 6 7 8 9]
now the new Diamention is: 1


In [53]:
m=np.array([[[[1,2,3],[46,85,96],[47,78,39]]]])
print(m)
print("Diamention is:",m.ndim)
arr=m.ravel()
print(arr)
print("Diamention is:",arr.ndim)

[[[[ 1  2  3]
   [46 85 96]
   [47 78 39]]]]
Diamention is: 4
[ 1  2  3 46 85 96 47 78 39]
Diamention is: 1


In [54]:
m=np.array([[[[1,2,3],[46,85,96],[47,78,39]]]])
print(m)
print("Diamention is:",m.ndim)
arr=m.flatten()
print(arr)
print("Diamention is:",arr.ndim)

[[[[ 1  2  3]
   [46 85 96]
   [47 78 39]]]]
Diamention is: 4
[ 1  2  3 46 85 96 47 78 39]
Diamention is: 1


# Unique Function

In [55]:
k=np.array([12,1,3,44,2,7,5,3,2,100,38,17,19,8,9,1,3])
print(k)
x=np.unique(k)
print(x)

[ 12   1   3  44   2   7   5   3   2 100  38  17  19   8   9   1   3]
[  1   2   3   5   7   8   9  12  17  19  38  44 100]


In [56]:
k=np.array([12,1,3,44,2,7,5,3,2,100,38,17,19,8,9,1,3])
print(k)
x=np.unique(k,return_index=True)
print(x)

[ 12   1   3  44   2   7   5   3   2 100  38  17  19   8   9   1   3]
(array([  1,   2,   3,   5,   7,   8,   9,  12,  17,  19,  38,  44, 100]), array([ 1,  4,  2,  6,  5, 13, 14,  0, 11, 12, 10,  3,  9]))


In [57]:
k=np.array([12,1,3,44,2,7,5,3,2,100,38,17,19,8,9,1,3])
print(k)
x=np.unique(k,return_index=True,return_counts=True)
print(x)

[ 12   1   3  44   2   7   5   3   2 100  38  17  19   8   9   1   3]
(array([  1,   2,   3,   5,   7,   8,   9,  12,  17,  19,  38,  44, 100]), array([ 1,  4,  2,  6,  5, 13, 14,  0, 11, 12, 10,  3,  9]), array([2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))


# Delete

In [58]:
a=np.array([1,2,3,4])
print(x)
m=np.delete(x,1,axis=0)
print(m)

(array([  1,   2,   3,   5,   7,   8,   9,  12,  17,  19,  38,  44, 100]), array([ 1,  4,  2,  6,  5, 13, 14,  0, 11, 12, 10,  3,  9]), array([2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))
[[  1   2   3   5   7   8   9  12  17  19  38  44 100]
 [  2   2   3   1   1   1   1   1   1   1   1   1   1]]


In [59]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
d= np.delete(x,1,axis=0)
print(d)

[[ 1  2  3  4]
 [ 9 10 11 12]]


# Insert

In [37]:
var=np.array([1,2,3,4,5,6,7])
print(var)
z= np.insert(var,2,100)
print(z)

[1 2 3 4 5 6 7]
[  1   2 100   3   4   5   6   7]


In [39]:
var=np.array([1,2,3,4,5,6,7])
print(var)
z= np.insert(var,(2,4),100)
print(z)

[1 2 3 4 5 6 7]
[  1   2 100   3   4 100   5   6   7]


In [40]:
var=np.array([1,2,3,4,5,6,7])
print(var)
z= np.insert(var,(2,4),6.55) #can give float value
print(z)

[1 2 3 4 5 6 7]
[1 2 6 3 4 6 5 6 7]


In [49]:
var5=np.array([[1,2,3],[4,5,6]])
#print(var5)
z= np.insert(var5,2,9,axis=0)
print(z)

[[1 2 3]
 [4 5 6]
 [9 9 9]]


In [6]:
var6=np.array([[1,2,3],[1,2,3]])

w= np.insert(var6,2,[22,23],axis=1)

print(w)

[[ 1  2 22  3]
 [ 1  2 23  3]]


In [8]:
var6=np.array([[1,2,3],[1,2,3]])

w= np.insert(var6,2,[22,23,24],axis=0)

print(w)

[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]


In [12]:
var7=np.array([[1,2,3,4,5,8]])

#w= np.insert(var6,2,[22,23,24],axis=0)
q=np.append(var7,66)

print(q)

[ 1  2  3  4  5  8 66]


In [13]:
var7=np.array([[1,2,3,4,5,8]])

#w= np.insert(var6,2,[22,23,24],axis=0)
q=np.append(var7,6.9)

print(q)

[1.  2.  3.  4.  5.  8.  6.9]


In [15]:
var7=np.array([[1,2,3],[4,5,8]])

#w= np.insert(var6,2,[22,23,24],axis=0)
q=np.append(var7,([[23],[24]]),axis=1)

print(q)


[[ 1  2  3 23]
 [ 4  5  8 24]]


In [19]:
var7=np.array([[1,2,3],[4,5,8]])

#w= np.insert(var6,2,[22,23,24],axis=0)
q=np.append(var7,[[23,24,27]],axis=0)

print(q)

[[ 1  2  3]
 [ 4  5  8]
 [23 24 27]]


In [11]:
var6=np.array([[1,2,3],[1,2,3]])

#w= np.insert(var6,2,[22,23,24],axis=0)
c=np.append(var6,[[40,90,70]],axis=0)

print(c)

[[ 1  2  3]
 [ 1  2  3]
 [40 90 70]]


# Search

In [61]:
var=np.array([1,2,3,1,5,6,7,1])
x=np.where(var == 2)
print(x)

(array([1]),)


In [66]:
var=np.array([4,2,3,1,5,6,7,1])
x=np.where((var/2)== 0)# no number equal to 0
print(x)

(array([], dtype=int64),)


In [67]:
var=np.array([4,2,3,1,5,6,7,1])
x=np.where((var%2)== 0)# no number equal to 0
print(x)

(array([0, 1, 5]),)


In [72]:
var1 =np.array([4,2,3,1,6,7,1])
#index          0,1,2,3,4,5,6,7,8
x = np.searchsorted(var1,5)
print(x)

4


In [74]:
var1 =np.array([4,2,3,1,6,7,1,9,10])
#index          0,1,2,3,4,5,6,7,8
x = np.searchsorted(var1,5,side="right")
print(x)

4


In [78]:
var1 =np.array([1,2,3,4,6,7,8,9,10])
#index          0,1,2,3,4,5,6,7,8
x = np.searchsorted(var1,[5,6,7],side="right")
print(x)

[4 5 6]


In [79]:
var1 =np.array([1,2,3,4,8,9,10])
#index          0,1,2,3,4,5,6,7,8
x = np.searchsorted(var1,[5,6,7],side="right")
print(x)

[4 4 4]


# Sort

In [81]:
var_1= np.array([1,4,2,3,5,7,9,6,10])

print(np.sort(var_1))

[ 1  2  3  4  5  6  7  9 10]


In [83]:
var_2= np.array(["a","f","t","s"])

print(np.sort(var_2))

['a' 'f' 's' 't']


In [84]:
var_3= np.array([[1,4,2],[3,5,7],[9,6,10]])

print(np.sort(var_3))

[[ 1  2  4]
 [ 3  5  7]
 [ 6  9 10]]


# Filter Array

In [9]:
var_4= np.array(["a","f","t","s"]) # print only True value

f=[True,False,True,False]
new_var= var_4[f]

print(new_var)
print(type(new_var))

['a' 't']
<class 'numpy.ndarray'>


# Shuffle 

In [14]:
v= np.array([1,2,3,4,5,6,7,8])
np.random.shuffle(v)
print(v)

[6 1 4 8 7 3 2 5]


# Resize

In [18]:
v1= np.array([1,2,3,4,5,6,7,8])
x=np.resize(v1,(2,3))
print(x)

[[1 2 3]
 [4 5 6]]


In [19]:
v2= np.array([1,2,3,4,5,6,7,8])
x=np.resize(v2,(3,2))
print(x)

[[1 2]
 [3 4]
 [5 6]]


# Arthimetic Operations


In [34]:
var=np.array([1,2,3,4])
varadd= var +3
print(varadd)

[4 5 6 7]


In [35]:
var=np.array([1,2,3,4])
varadd= var - 3
print(varadd)

[-2 -1  0  1]


In [36]:
var1=np.array([1,2,3,4])
var2=np.array([5,6,7,9])


varadd= var1 + var2
print(varadd)

[ 6  8 10 13]


In [38]:
var1=np.array([10,12,3,4])
var2=np.array([5,6,7,9])


varadd= var1 - var2
print(varadd)

[ 5  6 -4 -5]


In [39]:
var1=np.array([10,12,3,4])
var2=np.array([5,6,7,9])


varadd= var1 - var2
print(varadd)

[2.         2.         0.42857143 0.44444444]


In [42]:
var1=np.array([10,12,3,4])
var2=np.array([5,6,7,9])


varadd= var1 * var2
print(varadd)
print()

var1=np.array([10,12,3,4])
var2=np.array([5,6,7,9])


varadd= var1 % var2
print(varadd)



[50 72 21 36]

[0 0 3 4]


In [43]:
var=np.array([1,2,3,4])
varadd= var % 3
print(varadd)

[1 2 0 1]


![](pic.JPG)

In [57]:
var1=np.array([10,12,3,4])
var2=np.array([5,6,7,9])


varadd=np.add(var1,var2)
print(varadd)

var1=np.array([10,12,3,4])



var=np.add(var1,3)
print(var)


[15 18 10 13]
[13 15  6  7]


In [48]:
var1=np.array([10,12,3,4])
var2=np.array([5,6,7,9])


varadd=np.subtract(var1,var2)
print(varadd)


[ 5  6 -4 -5]


In [58]:
var1=np.array([10,12,3,4])
var2=np.array([5,6,7,9])


w=np.multiply(var1,var2)
print("multiply of var1 & var2: ",w)
print()

z=np.divide(var1,var2)
print("divide of var1 & var2: ",z)

print()
x=np.power(var1,var2)
print("power of var1 & var2",x)

print()
m=np.mod(var1,var2)
print("modulus of var1 & var2",m)

print()
v=np.reciprocal(var2)
print("reciprocal of var1 & var2",v)#[1 0 0 0]   # Because 1//2 = 0, 1//4 = 0, etc

multiply of var1 & var2:  [50 72 21 36]

divide of var1 & var2:  [2.         2.         0.42857143 0.44444444]

power of var1 & var2 [ 100000 2985984    2187  262144]

modulus of var1 & var2 [0 0 3 4]

reciprocal of var1 & var2 [0 0 0 0]


# 2-D Array

In [62]:
var1=np.array([[1,2,3],[4,5,6]])
var2=np.array([[1,2,3],[4,5,6]])

print(var1)
print()

print(var2)
print()


varadd1=np.add(var1,var2)
print(varadd1)



[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

[[ 2  4  6]
 [ 8 10 12]]


In [63]:
var1=np.array([1,2,3,4])

var=np.reciprocal(var1)
print(var)

[1 0 0 0]


![](pic1.JPG)

In [69]:
v1=np.array([36,3,1,4,5,8,6,7])

print("Min:",np.min(v1),"Position of Min:",np.argmin(v1))
print("Max:",np.max(v1),"Position of Max:",np.argmax(v1))
print("square:",np.sqrt(v1))






Min: 1 Position of Min: 2
Max: 36 Position of Max: 0
square: [6.         1.73205081 1.         2.         2.23606798 2.82842712
 2.44948974 2.64575131]


In [72]:
v2=np.array([[36,3,1,4],[5,8,6,7]])

print(np.min(v2,axis=0)) #axis=0 is column,axis=1 is row

[5 3 1 4]


In [73]:
v2=np.array([[36,3,1,4],[5,8,6,7]])

print(np.min(v2,axis=1)) #axis=0 is column,axis=1 is row

[1 5]


In [76]:
v3=np.array([5,8,6,7])

print(np.sin(v3))
print(np.cos(v3))
print(np.cumsum(v3))

[-0.95892427  0.98935825 -0.2794155   0.6569866 ]
[ 0.28366219 -0.14550003  0.96017029  0.75390225]
[ 5 13 19 26]


# Broadcasting with NumPy Arrays

1. Same Diamension
2. (1X3) (3X1)--->2nd Element of array is same or one array of 2nd element is 1  only right (3X1) in right element and 3X3 make array


In [77]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3])

print(var1+var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [79]:
var1=np.array([1,2,3])
print(var1.shape)
print()

print(var1)
print()

var2=np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()

print(var1+var2)


(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [85]:
x=np.array([[1],[2]])
print(x.shape)

y=np.array([[1,2,3],[4,5,6]])
print(y.shape)
print()

print(x+y)

(2, 1)
(2, 3)

[[2 3 4]
 [6 7 8]]


# NumPy Array Iterating

In [86]:
var=np.array([1,2,3,4])
print(var)
print()
for i in var:
    print(i)


    

[1 2 3 4]

1
2
3
4


In [88]:
var1=np.array([[1,2,3,4],[5,6,7,8]])
print(var1)
print()

for j in var1:
    print(j)

print()
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [90]:
var3=np.array([[[9,6,12,4],[5,6,7,8]]])
print(var3)
print()

for i in var3:
    for j in i:
        for k in j:
            print(k)
    


[[[ 9  6 12  4]
  [ 5  6  7  8]]]

9
6
12
4
5
6
7
8


In [92]:
var3=np.array([[[9,6,12,4],[5,6,7,8]]])
print(var3)
print()

for i in np.nditer(var3):
    print(i)

[[[ 9  6 12  4]
  [ 5  6  7  8]]]

9
6
12
4
5
6
7
8


In [4]:
import numpy as np
var3=np.array([[[9,6,12,4],[5,6,7,8]]])
print(var3)
print()

for i in np.nditer(var3,flags=["buffered"],op_dtypes="S"):
    print(i)

[[[ 9  6 12  4]
  [ 5  6  7  8]]]

np.bytes_(b'9')
np.bytes_(b'6')
np.bytes_(b'12')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')


In [9]:
import numpy as np

In [10]:

var3=np.array([[[9,6,12,4],[5,6,7,8]]])
print(var3)
print()

for i,d in np.ndenumerate(var3):
    print("index:",i,"Data:",d)

[[[ 9  6 12  4]
  [ 5  6  7  8]]]

index: (0, 0, 0) Data: 9
index: (0, 0, 1) Data: 6
index: (0, 0, 2) Data: 12
index: (0, 0, 3) Data: 4
index: (0, 1, 0) Data: 5
index: (0, 1, 1) Data: 6
index: (0, 1, 2) Data: 7
index: (0, 1, 3) Data: 8


# The Difference Between Copy and View

![](Pic2.jpeg)

In [16]:
var= np.array([1,2,3,4])
print("Var:",var)
x=var.copy()
print("Copy:",x)

Var: [1 2 3 4]
Copy: [1 2 3 4]


In [17]:
var1= np.array([1,2,3,4])
print("Var:",var1)
x=var1.view()
print("Veiw:",x)

Var: [1 2 3 4]
Veiw: [1 2 3 4]


In [19]:
var= np.array([1,2,3,4])

x=var.copy()

var[1]=100


print("Var:",var)
print("Copy:",x)

Var: [  1 100   3   4]
Copy: [1 2 3 4]


In [20]:
var= np.array([1,2,3,4])

x=var.view()

var[1]=40


print("Var:",var)
print("Copy:",x)

Var: [ 1 40  3  4]
Copy: [ 1 40  3  4]


#  Matrix

In [21]:
var=np.array([1,2,3,4,5])
print(var)
print(type(var))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [22]:
var1=np.matrix([1,2,3,4,5])
print(var1)
print(type(var1))

[[1 2 3 4 5]]
<class 'numpy.matrix'>


In [24]:
var1=np.matrix([[1,2],[4,5]])
var2=np.matrix([[1,2],[4,5]])

print(var1)
print(type(var1))
print(var1+var2)


[[1 2]
 [4 5]]
<class 'numpy.matrix'>
[[ 2  4]
 [ 8 10]]


In [25]:
var1=np.matrix([[1,2],[4,5]])
var2=np.matrix([[1,2],[4,5]])

print(var1)
print(type(var1))
print(var1-var2)

[[1 2]
 [4 5]]
<class 'numpy.matrix'>
[[0 0]
 [0 0]]


In [29]:
var1=np.matrix([[1,2],[4,5]])
var2=np.matrix([[1,2],[4,5]])

print(var1)
print(type(var1))
print()
print(var1*var2) # if multiply matrix is same boardcast(same size)
print()
print(var1.dot(var2))

[[1 2]
 [4 5]]
<class 'numpy.matrix'>

[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]


In [32]:
var1=np.matrix([[1,2,3],[4,5,6]])
var2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])


# if multiply matrix is same boardcast(same size)
# to multiply A.dot(B), the number of columns in A must equal the number of rows in B.
print()
print(var1.dot(var2))


[[30 36 42]
 [66 81 96]]


# Matrix Function


![](pic3.jpg)

In [34]:
var1=np.matrix([[1,2,3],[4,5,6]])

print(var1)
print()


print(np.transpose(var1))
print()

print(var1.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [36]:
var2=np.matrix([[1,2,3],[4,5,6]])

print(var2)
print()


print(np.swapaxes(var2,0,1))
print()

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]



In [38]:
var3=np.matrix([[1,2],[4,5]])

print(var3)
print()

print(np.swapaxes(var3,0,1))
print()


[[1 2]
 [4 5]]

[[1 4]
 [2 5]]



In [40]:
var3=np.matrix([[1,2],[3,4]])

print(var3)
print()

print(np.linalg.inv(var3))
print()

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]



In [41]:
var4=np.matrix([[1,2],[3,4]])

print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]



In [42]:
var5=np.matrix([[1,2],[3,4]])

print(var5)
print()

print(np.linalg.matrix_power(var5,0))
print()

[[1 2]
 [3 4]]

[[1 0]
 [0 1]]



In [44]:
var6=np.matrix([[1,2],[3,4]])

print(var6)
print()

print(np.linalg.matrix_power(var6,-2))
print()

[[1 2]
 [3 4]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [46]:
var7=np.matrix([[1,2],[3,4]])

print(var7)
print()

print(np.linalg.det(var7))
print()

[[1 2]
 [3 4]]

-2.0000000000000004



In [50]:
var8=np.matrix([[1,2,3],[3,4,6],[1,2,3]])

print(var8)
print()

print(np.linalg.det(var8))# zero beacause 2 rows is same
print()

[[1 2 3]
 [3 4 6]
 [1 2 3]]

0.0

