# Numpy:

Numpy is a low level library written in C & Fortrand for high level mathematical functions.
Numpy is use to overcomes the problem of running slower algorithms on running python by
using multidimensional arrays and functions that operate on arrays.Algorithm can
expressed as a function on arrays, allowing the algorithms to be run quickly.


# Why NumPy is Faster than Python Lists:

# 1. Continuous Memory (Compact Storage)

* Python List → Stores elements in different places in memory and only keeps references.
* NumPy Array → Stores elements next to each other in memory (like a C array). This makes
access much faster.

In [1]:
import numpy as np

In [3]:
py_list=[1,2,3,4,5]
np_array=np.array([1,2,3,4,5])
print("Python list element addresses:")
for x in py_list:
    print(id(x))
    
print("\nNumPy array element addresses:")
print(np_array.__array_interface__["data"])



Python list element addresses:
140724303934376
140724303934408
140724303934440
140724303934472
140724303934504

NumPy array element addresses:
(1701424780960, False)


# 2. Vectorization (No Loops in Python) spark


* Python List → You must use loops.
* NumPy Array → Can apply operations to the whole array at once. Internally, NumPy uses
fast C code, not slow Python loops

In [4]:
# Python list with normal for loop
list_data=[1,2,3,4,5]
list_result=[]
for x in list_data:
    list_result.append(x*2)
print("Python List:",list_result)

# NumPy array (vectorized)
np_array=np.array([1,2,3,4,5])
np_data=np_array*2
print("Numpy Array",np_data)

Python List: [2, 4, 6, 8, 10]
Numpy Array [ 2  4  6  8 10]


# 3. Same Data Type (Homogeneous Data):


* Python List → Can store mixed types, e.g. [1, "hello", 3.5]. That means Python must check
the type of each element again and again.

* NumPy Array → Stores only one compact data
type (common type of all elements). This makes operations much faster.

In [8]:
py_list=[1,"Hello",True,22,56.66,900,"p"]
np_array=np.array([1,2,3,4,5,6])
Type_list=[]
for x in py_list:
    Type_list.append(type(x))
print("Python list types:",Type_list)
print("Numpy Array types:",np_array.dtype)





Python list types: [<class 'int'>, <class 'str'>, <class 'bool'>, <class 'int'>, <class 'float'>, <class 'int'>, <class 'str'>]
Numpy Array types: int64


# What happens if we put mixed data types in a NumPy array?

Unlike Python lists (which can hold elements of different types without any issue), NumPy
arrays always enforce a single data type for all elements.If you mix different types, NumPy
will automatically convert all elements to one common type that can fit everything.

In [11]:
#Example 1 ---> int + str
np_array=np.array([1,2,"hello",3])

print(np_array)
print("Array dtype: ",np_array.dtype)


# The integers (1, 2, 3) were converted into strings ('1', '2', '3').
# NumPy decided the final type should be string, because a string can represent both integer & float
# <U11 means “Unicode string of maximum length 21”.

['1' '2' 'hello' '3']
Array dtype:  <U21


In [15]:
# Example 2 ----> float + int
np_array1=np.array([1.22,1,3,7,5.5])

print("Array:",np_array1)
print("Array dtype: ",np_array1.dtype)


# The integers (1, 2, 4) were converted into floats (1.0, 2.0, 4.0).
# NumPy chose float64 because floats can hold decimal values, and they can also hold interger


Array: [1.22 1.   3.   7.   5.5 ]
Array dtype:  float64


In [17]:
# Example 3 -----> int + bool
np_array2=np.array([1,True,3,7,False])

print("Array:",np_array2)
print("Array dtype: ",np_array2.dtype)


# True was converted to 1, and False was converted to 0.
# NumPy chose int64, since integers can represent both numbers and booleans.


Array: [1 1 3 7 0]
Array dtype:  int64


# 1. Creating Numpy Array

In [2]:
# import numpy library
import numpy as np

In [3]:
#creating numpy array
arr=np.array([1,2,3,4,5]) #convert list to numy array

#vector
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# creating 2D array
arr1=np.array([[1,2,3],[4,5,6]])

print(arr1)
print(type(arr1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
# creating array of zeros
arr2=np.zeros((2,3)) #--->2Row & 3column
print(arr2)


[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
arr3=np.zeros((3,4)) # (3,4) ---> 3 rows, 4 columns
print(arr3)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# creating array of ones
arr4=np.ones((3,4)) #---> 3 rows, 4 columns
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# creating identity matrics
arr5=np.identity((5))
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# creating array using arange
# arange ----> counter of range function of python
arr6=np.arange(10)

print(arr6)
print(type(arr6))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [10]:
# creating array using arange
arr6=np.arange(10,25)

print(arr6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [11]:
# creating array using arange
arr6=np.arange(10,25,2)

print(arr6)

[10 12 14 16 18 20 22 24]


In [12]:
# creating array using linspace ----> useto make equi-distance between the element
arr7=np.linspace(0,20,10)

print(arr7)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [13]:
# creating array using linspace ----> useto make equi-distance between the element
arr7=np.linspace(4,20,5)

print(arr7)

[ 4.  8. 12. 16. 20.]


# 2. Numpy Array Properties & Attributes


# shape

In [14]:
# find shape of array ----> return the dimension of array (rows, columns)

print(arr) #array has 5 elements in one dimension.
print(arr.shape)

[1 2 3 4 5]
(5,)


In [15]:
print(arr4) # (3 rows,4 columns)

print()

print(arr4.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

(3, 4)


In [16]:
# creating multidimensional array space
arr8=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(arr8)
print(arr8.shape) #(2 rows, 2 columns, 2 matrices)




[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


# ndim


In [17]:
#ndim -----> return the dimension of numpy array
print(arr8)
print(arr8.ndim)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [45]:
#ndim -----> return the dimension of numpy array

print(arr5)
print(arr5.ndim)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2


#  size

In [46]:
#size ---->return number of items
print(arr8)
print(arr8.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8


# itemsize


In [48]:
#itemsize ----> return how much memory each array element uses in bytes.

print(arr8)
print(arr8.itemsize)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8


# dtype

In [50]:
#dtype ----> return data-type of array

print(arr8)
print(arr8.dtype)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
int64


# astype

In [52]:
#astype ----> use to convert the data type of array

print(arr8)
print(arr8.dtype)

print(arr8.astype("float"))
print(arr8)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
int64
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# List Vs Numpy-Array:


* Less Memory

In [53]:
import sys

In [55]:
py_list_range=list(range(1000))
np_array_range=np.arange(1000)

print("Python list size:",sys.getsizeof(py_list_range),"bytes")
print("Numpy Array size:",np_array_range.nbytes,"bytes")


Python list size: 8056 bytes
Numpy Array size: 8000 bytes


* Faster

In [18]:
import time

In [20]:
#Faster -----> Numpy array operational speed much faster than list oerations
#python list
py_list=list(range(1000000))
start=time.time()
py_result=[]
for x in py_list:
    py_result.append(x*2)

end=time.time()
print("Python list time:", end - start, "seconds")

#Numpy Array
np_list=np.arange(1000000)
start=time.time()
np_data=np_list*2 # Vectorized operation
end=time.time()
print("Numpy Array Time time:", end - start, "seconds")




Python list time: 0.20302128791809082 seconds
Numpy Array Time time: 0.0034072399139404297 seconds


* Convenient


In [25]:
#Convenient -----> NumPy is simpler and cleaner, this makes numpy more convenient.

# Adding two lists element by element using pyhon operation
import numpy as np
p1=[1,2,3,4,5,6]
p2=[10,20,90,100,30,40]
Py_result=[]
for x in range(len(p1)):
    Py_result.append(p1[x]+p2[x])
print("Python list of two Number:",Py_result)

# Adding two lists element by element using numpy operation
n1=np.array([1,2,3,4,5,6])
n2=np.array([10,20,90,100,30,40])
var= n1 + n2

print("Numpy Array of two Number:",var)

Python list of two Number: [11, 22, 93, 104, 35, 46]
Numpy Array of two Number: [ 11  22  93 104  35  46]


# Indexing & Slicing In Numpy


In [32]:
#simple array
arr9=np.arange(24)

print(arr9)

#indexing
print(arr9[7])
print(arr9[-1])

#slicing
print(arr9[7:10])
print(arr9[-6:-1])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
7
23
[7 8 9]
[18 19 20 21 22]


In [42]:
# Multidimensional matrics
# reshape---> convert the array into given matrics size
arr10=np.arange(24).reshape((6,4)) # reshape : converts the array into given matrics(Row,column)

print(arr10)

print()
#indexing
print(arr10[2]) # retrun row

print()

#sciling
print(arr10[2:5])
print()

#slcing rows & columns ------> arr(slice rows , slice column)

print(arr10[:,2]) #return rows & column
print()

print(arr10[:,1:4]) #return rows & column
print()

print(arr10[4:6,2:4]) #return rows & column
print()



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[ 8  9 10 11]

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[ 2  6 10 14 18 22]

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]
 [21 22 23]]

[[18 19]
 [22 23]]



In [64]:
#multiblock & multidimensional matrics
arr11=np.arange(32).reshape((2,4,4)) #(block,row,column)
print(arr11)

#indexing
print(arr11[0])#first block
print(arr11[1])#second block

print(arr11[0][0])#first block first row

print(arr11[1][0])#second block first row

print(arr11[0][0][1])  # frist block row 1 col 2
print(arr11[1][0][1])  # Second block row 1 col 2

#slicing
print(arr11[:][0][0]) # All blocks, first row, first col
print(arr11[:][1][1]) # All blocks, second row, second col

print(arr11[0][:][:]) # Entire first block
print(arr11[1][:][:]) # Entire second block

print(arr11[:][:][0])# All blocks, all rows


print(arr11[:][:][1])# All blocks, all rows


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[0 1 2 3]
[16 17 18 19]
1
17
[0 1 2 3]
[20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


# Numpy Iteration

In [62]:
for i in arr10:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [63]:
#print item wise
for i in np.nditer(arr10):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [66]:
print(arr11)
#print item wise in one block
for i in np.nditer(arr11[0]):
    print(i)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


# Numpy Operation


In [80]:
var1=np.array([1,2,3,4,5])
var2=np.array([3,7,8,9,10])

print(var1)
print(var2)

[1 2 3 4 5]
[ 3  7  8  9 10]


In [81]:
#Addition
print(var1+var2)
print()
#Subraction
print(var1-var2)
print()

#Multiplication
print(var1*var2) #vector multiplication
print()

print(var1*2) #Scalar multiplication
print()

#Division
print(var1/var2)  #vector division
print()

print(var2/2)  #Scalar division


[ 4  9 11 13 15]

[-2 -5 -5 -5 -5]

[ 3 14 24 36 50]

[ 2  4  6  8 10]

[0.33333333 0.28571429 0.375      0.44444444 0.5       ]

[1.5 3.5 4.  4.5 5. ]


In [82]:
print(var1>3)
print(var1==var2)
print(var2>=5)

[False False False  True  True]
[False False False False False]
[False  True  True  True  True]
